name: PR Title Validation

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - labeled
      - unlabeled

jobs:
  validate_pr_title:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR title
      run: |
        #pr_title="${{ github.event.pull_request.title }}"
        pr_title="fix: subject [OCH-123]"
        pattern="^((feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-zA-Z0-9\s_-]+\))?!?:\s[^\s].*?\s\[[A-Z]+-\d+\].*)$"
        SKIP_LABEL="autorelease: pending"
        pr_labels="${{ toJSON(github.event.pull_request.labels) }}"
        
        if [[ ${pr_labels} == *"${SKIP_LABEL}"* ]]; then
          echo "Skipping PR title validation due to the presence of the '${SKIP_LABEL}' label"
          exit 0
        fi

        if [[ ! ${pr_title} =~ ${pattern} ]]; then
          echo -e "\033[31mInvalid PR title\033[0m"
          echo "Please follow the Conventional Commits convention and append a JIRA ID, e.g: 'feat(scope): subject [OCH-123]' or 'fix: subject [OCH-123]'"
          echo -e "\033[90mmore info: https://www.conventionalcommits.org/en/v1.0.0/\033[0m"
          exit 1
        fi