name: PR Title Validation

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - labeled
      - unlabeled

jobs:
  validate_pr_title:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR title
      run: |
        pr_title="${{ github.event.pull_request.title }}"
        PR_TITLE_RE="^(?=.{1,90}$)(?:build|feat|ci|chore|docs|fix|perf|refactor|revert|style|test|wip)(?:\(.+\))*(?::).{4,}(?:\s\[OCH-\d+\])(?:#\d+)*(?<![\.\s])$"
        SKIP_LABEL="autorelease: pending"
        pr_labels="${{ toJSON(github.event.pull_request.labels) }}"
        
        if [[ ${pr_labels} == *"${SKIP_LABEL}"* ]]; then
          echo "Skipping PR title validation due to the presence of the '${SKIP_LABEL}' label"
          exit 0
        fi

        if [[ ! ${pr_title} =~ ${PR_TITLE_RE} ]]; then
          echo "error: invalid PR title"
          echo "Valid PR title is required to match pattern: ^(?=.{1,90}$)(?:build|feat|ci|chore|docs|fix|perf|refactor|revert|style|test|wip)(?:\(.+\))*(?::).{4,}(?:\s\[OCH-\d+\])(?:#\d+)*(?<![\.\s])$"
          exit 1
        fi
