name: PR Validation

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"

          echo "Validating PR title: '$PR_TITLE'"
          if ! echo "$PR_TITLE" | grep -qE "^(fix|feat|refactor)(\!)?\: .+"; then
            echo "error: invalid PR title"
            echo "Valid PR titles must follow the Conventional Commit message format:"
            echo "- fix: for bug fixes (SemVer patch)"
            echo "- feat: for new features (SemVer minor)"
            echo "- feat!: or fix!:, refactor!:, etc. for breaking changes (SemVer major)"
            echo "Please update the PR title and try again."
            exit 1
          fi
          echo "PR title validation passed!"
