on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          pull-request-header: ":robot: *beep* *boop* I have created a release"
          extra-files: |
            Services/GearsMonoRepoSample.Finance.Web.Api/GearsMonoRepoSample.Finance.Web.Api.csproj
            
          # extra-files: |
          #   [
          #     {
          #       "type": "xml",
          #       "path": "Services/GearsMonoRepoSample.Finance.Web.Api/GearsMonoRepoSample.Finance.Web.Api.csproj",
          #       "xpath": "//Project/PropertyGroup/Version"
          #     }
          #   ]
